### ISSUE TITLE
AES Key可以确定是dbEncryptKey

### ISSUE THREAD

**Issue by Mas0nShi** [TinyNiko/mac_wxapkg_decrypt#1]
hook得到的aes key来自`-[AuthSectResp init]`中的置入的`SetCliDbencryptKey`，提取对应目录下的聊天记录`msg_*.db`可以使用此key解开得到聊天记录。

**Comment by TinyNiko** [comment]
看了一下确实是数据库的key， 数据库用了32个字节的key， 小程序这边使用的是前16个字节

**Comment by TinyNiko** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/7581263/171991286-0456da21-a1b0-4e9f-bd2b-0acf209fc824.png">

从图上看，感觉是从通过请求获取的key， 如果是这样的话，这个key 算法就无法逆向了...

**Comment by Mas0nShi** [comment]
dbEncryptKey确实是来源于server
目前猜测是server通过设备的一些指纹以及uid计算得到固定的dbEncryptKey
唯一值得欣慰的是在同一设备上反复登录，dbEncryptKey不会改变...不必反复hook获取key🤣
