### ISSUE TITLE
TypeError: cannot read property '+ pkgDecrypt:' of undefined

### ISSUE THREAD

**Issue by longyi-xw** [TinyNiko/mac_wxapkg_decrypt#10]
frida 16.0.19
python 3.10.9
mac m1

frida pid -l _agant.js
就直接报错了
<img width="747" alt="image" src="https://github.com/TinyNiko/mac_wxapkg_decrypt/assets/54786937/d24bdf34-7d58-4eb3-a9da-9e75a916435f">

**Comment by TinyNiko** [comment]
由于我没有m1， 所以可能就需要找有缘人分析一下了
