### ISSUE TITLE
微信3.8版本似乎逻辑都变了

### ISSUE THREAD

**Issue by lzj0223** [TinyNiko/mac_wxapkg_decrypt#12]
大神有没有空研究3.8版本的

**Comment by TinyNiko** [comment]
今天刚想搞个小程序， 忽然发现问题了，这个月有空就看看，看下来变化挺大的。

**Comment by TinyNiko** [comment]
/Users/xxx/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet/packages 下面的wxxxxxx/数字/__APP__.wxapkg  就是小程序包，这个包未加密，可以直接使用工具还原

**Comment by LaurenBerrys** [comment]
Version. 3.8.10 (28633)现在好像不行呀没看到
