### ISSUE TITLE
 mac m1 报错 fstat$INODE64

### ISSUE THREAD

**Issue by jingyan6** [TinyNiko/mac_wxapkg_decrypt#2]
Failed to attach: unable to bind, “fstat$INODE64” not found in “/usr/lib/libSystem.B.dylib”

**Comment by jingyan6** [comment]
@TinyNiko 
怎么解

**Comment by TinyNiko** [comment]
这个应该是frida 的报错吧， 我没有m1, 这个暂时解不了😅。  还有一种方式是使用lldb ，可以参考 https://blog.csdn.net/swinfans/article/details/88712593
