### ISSUE TITLE
微信版本 Version. 3.6.1 (24205)  操作失败

### ISSUE THREAD

**Issue by jasonsoft-net** [TinyNiko/mac_wxapkg_decrypt#4]
❯ sudo frida 84348 -l _agent.js
Password:
     ____
    / _  |   Frida 16.0.8 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to Local System (id=local)
Failed to attach: unable to access process with pid 84348 from the current user account

**Comment by TinyNiko** [comment]
是不是mac的SIP 没有关
